name: .NET Framework Build and Deploy

on:
  push:
    branches: [ main ]  # 這裡設置了主分支，根據需要修改

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows runner，因為 .NET Framework 需要在 Windows 環境中編譯和運行

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET Framework
      run: |
        # 安裝 .NET Framework 4.8 SDK
        choco install netfx-4.8

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: |
        nuget restore MyApp.sln  # 替換成你的解決方案檔案路徑

    - name: Build the .NET Framework solution
      run: |
        msbuild.exe MyApp.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl=release"

    - name: Publish .NET Framework Project
      run: |
        # 如果需要部署到指定目錄或其他操作，請在這裡添加步驟
        MSBuild MyApp.sln /p:Configuration=Release /p:OutputPath=release

    - name: Commit to GitHub Pages (if needed)
      uses: peaceiris/actions-gh-pages@v3   #Settings→Actions→General→Workflowpermissions中，確保GITHUB_TOKEN具有write權限，而不是僅有read權限。
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./release
